apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: telecom
    isDefault: true
    editable: false
    jsonData:
      database: telecom
      sslmode: disable
      maxOpenConns: 8
      maxIdleConns: 4
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: telecom
